In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("../data/raw/telcom.csv")

In [7]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [9]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop(columns=["customerID"],inplace=True)

In [12]:
categorical_columns=df.select_dtypes(include="str").columns
categorical_columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn'],
      dtype='str')

In [13]:
for col in categorical_columns:
    print(col+": "+f"[{df[col].unique()}]")
    print()

gender: [<StringArray>
['Female', 'Male']
Length: 2, dtype: str]

Partner: [<StringArray>
['Yes', 'No']
Length: 2, dtype: str]

Dependents: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

PhoneService: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

MultipleLines: [<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str]

InternetService: [<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str]

OnlineSecurity: [<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str]

OnlineBackup: [<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str]

DeviceProtection: [<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str]

TechSupport: [<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str]

StreamingTV: [<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str]

StreamingMovies: [<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str]

Contract: [<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str]

PaperlessBilling: [<StringArray>
['Yes', 'No']
Length: 2, dtype: str]

PaymentMethod: [<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str]

TotalCharges: [<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str]

Churn: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

In [14]:
df["TotalCharges"]=df["TotalCharges"].replace(' ',float("nan"))

In [15]:
df["TotalCharges"]=df["TotalCharges"].astype("float64")

In [16]:
df["TotalCharges"].isnull().sum()

np.int64(11)

In [17]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [18]:
df.dropna(inplace=True)

In [19]:
internet_cols = [
    "OnlineSecurity", "OnlineBackup", "DeviceProtection",
    "TechSupport", "StreamingTV", "StreamingMovies"
]

phone_cols = ["MultipleLines"]

df[internet_cols] = df[internet_cols].replace("No internet service", "No")
df[phone_cols]    = df[phone_cols].replace("No phone service", "No")

In [20]:
for col in categorical_columns:
    print(col+": "+f"[{df[col].unique()}]")
    print()

gender: [<StringArray>
['Female', 'Male']
Length: 2, dtype: str]

Partner: [<StringArray>
['Yes', 'No']
Length: 2, dtype: str]

Dependents: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

PhoneService: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

MultipleLines: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

InternetService: [<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str]

OnlineSecurity: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

OnlineBackup: [<StringArray>
['Yes', 'No']
Length: 2, dtype: str]

DeviceProtection: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

TechSupport: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

StreamingTV: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

StreamingMovies: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

Contract: [<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str]

PaperlessBilling: [<StringArray>
['Yes', 'No']
Length: 2, dtype: str]

PaymentMethod: [<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str]

TotalCharges: [[  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]]

Churn: [<StringArray>
['No', 'Yes']
Length: 2, dtype: str]

In [21]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [22]:
print(type(categorical_columns))

<class 'pandas.Index'>